version: '3.8'
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=199765
    ports:
      - '5433:5432'
    volumes:
      - volpsql:/var/lib/postgresql/data
volumes:
  volpsql:
    driver: local

